### ISSUE TITLE
Wrong publish 

### ISSUE THREAD

**Issue by PabloSzx** [danielmhanover/typeorm-upsert#1]
![Screenshot from 2019-08-16 13-49-40](https://user-images.githubusercontent.com/8672915/63187378-bc320700-c02c-11e9-88b2-729e5437ff7c.png)

The [npm-package](https://www.npmjs.com/package/typeorm-upsert) is published wrong, as you can see, the files are empty

**Comment by brianschardt** [comment]
Yes this is incorrect trying to use this package but it doesnt work. @danielmhanover

**Comment by cdeutsch** [comment]
At least one issue, is the `main` setting in package.json is incorrect.

Here's another TypeScript based NPM you can reference for publishing an NPM
https://github.com/cdeutsch/puppeteer-request-intercepter

**Comment by yagoferrer** [comment]
I experienced the same issue @danielmhanover . Please fix the package.json so that we can use your module using `npm install`

**Comment by theoparis** [comment]
It still doesn't work for me, and it seems like you didn't publish the new version to npm? Is this package discontinued?
