### ISSUE TITLE
Can't support camelCase columns - wrong build of setter_string

### ISSUE THREAD

**Issue by mkobi** [danielmhanover/typeorm-upsert#2]
I'm using postgres, which uses lowercase on statements which will cause an error while trying to update if using camel-case column names.
To solve this simply replace this line:
``` const setter_string = keys.map(k => `${opts ? opts.key_naming_transform(k) : k} = :${k}`) ```

With this line:
``` const setter_string = keys.map(k => `"${opts ? opts.key_naming_transform(k) : k}" = :${k}`) ```

**Comment by brianschardt** [comment]
@mkobi have you gotten this to work in typescript?
